[package]
name = "aincradfs-path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qp-trie = "0.8"
widestring = "1"
bstr = "1"
bytemuck = "1"